apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP        
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80           # the port your Ingress will expose
      targetPort: 80     
