apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway-container
        image: us-central1-docker.pkg.dev/swift-hope-460410-d5/my-docker-repo/adeel2k01/gateway-service
        ports:
        - containerPort: 8080
        env:
        - name: INFERENCE_API_URL
          valueFrom:
            secretKeyRef:
              name: gateway-secret
              key: INFERENCE_API_URL
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: gateway-secret
              key: MONGO_URI
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
