apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  INFERENCE_API_URL: "https://pegasus-glad-panther.ap.ngrok.io"
  MONGO_URI:         "mongodb://mongo:27017/chatlogs"
