apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
stringData:
  INFERENCE_API_URL: "https://pegasus-glad-panthe.jp.ngrok.io"
  MONGO_URI:         "mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017/chatlogs?replicaSet=rs0"

